### ISSUE TITLE
Rolling TODO List

### ISSUE THREAD

**Issue by jordanbtucker** [json5/json5-dotnet#1]
**v1.0.0** (TODO list not yet finalized)
- [x] Write tests for public API.
- [x] Write tests for syntax errors with lines, and columns.
- [ ] Write CLI and tests.
- [ ] Add missing documentation.
- [ ] Add support for serialization.
- [ ] Move error messages to resource file.
